class gameStateInstance:
	oppTypePower: int
	oppTypeInt: int
	oppTypeSpeed: int
	oppCd0: int
	oppCd1: int
	oppCd2: int
	oppCd3: int
	oppCd4: int
	oppLastAtt0: int
	oppLastAtt1: int
	oppLastAtt2: int
	oppLastAtt3: int
	oppLastAtt4: int
	oppDmg: float
	oppHealth: float
	selfTypePower: int
	selfTypeInt: int
	selfTypeSpeed: int
	selfCd0: int
	selfCd1: int
	selfCd2: int
	selfCd3: int
	selfCd4: int
	selfLastAtt0: int
	selfLastAtt1: int
	selfLastAtt2: int
	selfLastAtt3: int
	selfLastAtt4: int
	selfDmg: float
	selfHealth: float 